### ISSUE TITLE
Getting a list of warning while running the extend_PE_reads.pl

### ISSUE THREAD

**Issue by amrita1983** [homeveg/nuctools#9]
Please help me to know whether we can proceed with this errors in extend_PE_reads.pl program or not 

Use of uninitialized value in split at /export/apps/nuctools-master/extend_PE_reads.pl line 179, <$inFH> line 5680.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 184, <$inFH> line 5680.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 185, <$inFH> line 5680.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5680.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5680.
Use of uninitialized value in scalar chomp at /export/apps/nuctools-master/extend_PE_reads.pl line 176, <$inFH> line 5681.
Use of uninitialized value in split at /export/apps/nuctools-master/extend_PE_reads.pl line 179, <$inFH> line 5681.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 184, <$inFH> line 5681.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 185, <$inFH> line 5681.
Use of uninitialized value in subtraction (-) at /export/apps/nuctools-master/extend_PE_reads.pl line 186, <$inFH> line 5681.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5681.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5681.
Use of uninitialized value in scalar chomp at /export/apps/nuctools-master/extend_PE_reads.pl line 176, <$inFH> line 5683.
Use of uninitialized value in split at /export/apps/nuctools-master/extend_PE_reads.pl line 179, <$inFH> line 5683.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 184, <$inFH> line 5683.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 185, <$inFH> line 5683.
Use of uninitialized value in subtraction (-) at /export/apps/nuctools-master/extend_PE_reads.pl line 186, <$inFH> line 5683.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5683.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5683.
Use of uninitialized value in scalar chomp at /export/apps/nuctools-master/extend_PE_reads.pl line 176, <$inFH> line 5684.
Use of uninitialized value in split at /export/apps/nuctools-master/extend_PE_reads.pl line 179, <$inFH> line 5684.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 184, <$inFH> line 5684.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 185, <$inFH> line 5684.
Use of uninitialized value in subtraction (-) at /export/apps/nuctools-master/extend_PE_reads.pl line 186, <$inFH> line 5684.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5684.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5684.
Use of uninitialized value in scalar chomp at /export/apps/nuctools-master/extend_PE_reads.pl line 176, <$inFH> line 5685.
Use of uninitialized value in split at /export/apps/nuctools-master/extend_PE_reads.pl line 179, <$inFH> line 5685.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 184, <$inFH> line 5685.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 185, <$inFH> line 5685.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5685.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5685.
Use of uninitialized value in scalar chomp at /export/apps/nuctools-master/extend_PE_reads.pl line 176, <$inFH> line 5688.
Use of uninitialized value in split at /export/apps/nuctools-master/extend_PE_reads.pl line 179, <$inFH> line 5688.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 184, <$inFH> line 5688.
Use of uninitialized value in subroutine entry at /export/apps/nuctools-master/extend_PE_reads.pl line 185, <$inFH> line 5688.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5688.
Use of uninitialized value in string eq at /export/apps/nuctools-master/extend_PE_reads.pl line 191, <$inFH> line 5688.
Use of uninitialized value in scalar chomp at /export/apps/nuctools-master/extend_PE_reads.pl line 176, <$inFH> line 5689.

**Comment by homeveg** [comment]
Hi, if the issue is still opened, can you please write me the command line you used to start a script and what kind of data you are loading? It seems you have several empty lines at the end of your input file. Try to remove it with a text editor.
To suppress all warning, you can run a script without -w option, like following:
`perl /export/apps/nuctools-master/extend_PE_reads.pl`
